// Alias curados: propuesta del dueño -> nombre EXACTO en moleculas_referencias.
// Cada entrada se sustenta en el diagnostico de similitud (_diag_nomatch.txt).
export const ALIAS = {
  'acido acetilsalicilico': 'Acetilsalicilico Acido',
  'carbonato de calcio': 'Calcio Carbonato',
  'cloruro de sodio': 'Sodio Cloruro',
  'ciprofloxacina': 'Ciprofloxacino',
  'sildenafil': 'Sildenafilo',
  'acido valproico': 'Valproico Acido',
  'acido clavulanico': 'Clavulanico Acido',
  'acido ibandronico': 'Ibandronico Acido',
  'acido azelaico': 'Azelaico Acido',
  'acido ursodesoxicolico': 'Ursodeoxicolico Acido',
  'acido ursodeoxicolico': 'Ursodeoxicolico Acido',
  'citrato de potasio': 'Citrato Potasio',
  'trimetoprim': 'Trimetoprima',
  'hidroxicina': 'Hidroxizina',
  'hioscina butilescopolamina': 'Butilescopolamina Bromuro',
  'n butil bromuro de hioscina': 'Butilescopolamina Bromuro',
  'butil bromuro de hioscina': 'Butilescopolamina Bromuro',
  'vitamina d colecalciferol': 'Colecalciferol',
  'vitamina d3 colecalciferol': 'Colecalciferol',
  'vitamina c acido ascorbico': 'Ascorbico Acido',
  'metamizol dipirona': 'Metamizol',
  'peroxido de hidrogeno agua oxigenada': 'Peroxido De Hidrogeno',
  'iodopovidona': 'Povidona Iodada',
  'fosfato disodico': 'Fosfato Disodio',
  'fosfato de sodio dibasico': 'Fosfato Disodio',
  'fosfato de sodio': 'Sodio Fosfato',
  'bencilpenicilina benzatinica': 'Bencilpenicilina-benzatina',
  'bencilpenicilina procaina': 'Bencilpenicilina Procaina',
  'penicilina g procaina': 'Bencilpenicilina Procaina',
  'penicilina g sodica': 'Penicilina G',
  'piridoxina vitamina b6': 'Piridoxina',
  'benzydamina': 'Bencidamina',
  'senosidos': 'Senosidos A-b',
  'sulfadiazina de plata': 'Sulfadiazina Argentica',
  'hialuronato de sodio': 'Hialuronico Acido',
  // --- alias agregados 2026-09-25 tras el veredicto del dueno en los CSV de conflictos/revision ---
  'butilbromuro de hioscina': 'Butilescopolamina Bromuro',
  'carboximetilcisteina': 'S-carboximetilcisteina',
  'cloruro de cetilpiridinio': 'Cetilpiridinio Cloruro',
  'fosfato de sodio monobasico': 'Fosfato Monosodio Dihidrato',
  'fosfato monosodico': 'Fosfato Monosodio Dihidrato',
  'hierro como sulfato ferroso': 'Hierro (ii) Sulfato',
  'lactobacillus casei variedad rhamnosus': 'Lactobacillus Rhamnosus',
  'macrogol': 'Macrogol 3350',
  'polietilenglicol 3350': 'Macrogol 3350',
  'penicilina g benzatinica': 'Bencilpenicilina-benzatina',
  'penicilina g potasica': 'Bencilpenicilina Potasica',
  'penicilina g procainica': 'Bencilpenicilina Procaina',
  // --- alias verificados contra la BD 2026-09-25 (existen en moleculas_referencias) ---
  'bromexina': 'Bromhexina',                      // typo del nombre comercial, no "fuera de CIMA"
  'bromexina clorhidrato': 'Bromhexina',
  'finasteride': 'Finasterida',
  'nimodipina': 'Nimodipino',
  'gluconato ferroso': 'Gluconato Hierro',
  'diclofenac potasico': 'Diclofenaco',
  'diclofenac dietilamino': 'Diclofenaco Dietilamina',
  'diclofenaco dietilamino': 'Diclofenaco Dietilamina',
  'pinaverium bromuro': 'Pinaverio Bromuro',
  'hioscina n butilbromuro': 'Butilescopolamina Bromuro',
  'butilbrom hioscina': 'Butilescopolamina Bromuro',
  'cloruro sodico': 'Sodio Cloruro',
  'gluconato de calcio': 'Gluconato Calcio Monohidrato',
  'cloruro de calcio': 'Calcio Cloruro',
  // 2026-09-25: marcas resueltas por el dueno
  'algio': 'Bisoprolol',
  'apiret': 'Acetaminofen',
  'cifarcaina': 'Lidocaina',
  'gluconato calcio': 'Gluconato Calcio Monohidrato',
  'agua para preparaciones inyectables': 'Agua Para Preparaciones Inyectables',
  'agua bidestilada': 'Agua Para Preparaciones Inyectables',
  'agua destilada': 'Agua Para Preparaciones Inyectables',
  'polisulfato de mucopolisacarido': 'Condroitina Sulfato Sodio',
  'factor de coagulacion viii': 'Factor Viii Humano',
  'factor antihemofilico viii': 'Factor Viii Humano',
  // 2026-09-26: las 15 moleculas nuevas creadas con ATC (ids 4284-4298)
  'citrato calcio': 'Citrato de Calcio',
  'calcio citrato': 'Citrato de Calcio',
  'nitazoxanido': 'Nitazoxanida',
  'lactasa': 'Tilactasa',
  'lactasa enzima': 'Tilactasa',
  'beta galactosidasa': 'Tilactasa',
  'bacillus clausii': 'Esporas de Bacillus clausii',
  'bacillus clausii esporas': 'Esporas de Bacillus clausii',
  'subsalicilato de bismuto': 'Bismuto Subsalicilato',
  'bismuto subsalicilato': 'Bismuto Subsalicilato',
  'complejo b': 'Vitaminas del Complejo B',
  'complejo de vitamina b': 'Vitaminas del Complejo B',
  'complejo vitamina b1 b2 b6 b12': 'Vitaminas del Complejo B',
  'vitaminas del grupo b': 'Vitaminas del Complejo B',
  'sales de rehidratacion oral': 'Sales de Rehidratación Oral',
  'rehidrosol': 'Sales de Rehidratación Oral',
  'alcohol polivinilico': 'Alcohol Polivinílico',
  'polivinil alcohol': 'Alcohol Polivinílico',
  'magnesio bisglicinato': 'Magnesio Glicinato',
  'bisglicinato de magnesio': 'Magnesio Glicinato',
  'lisados bacterianos': 'Lisado Bacteriano',
  'lisado de bacterias': 'Lisado Bacteriano',
  'aminoacidos cristalinos': 'Aminoácidos',
  'aminoacidos libres': 'Aminoácidos',
  'triticum vulgare': 'Extracto Acuoso de Triticum vulgare',
  'fenoxietanol': 'Extracto Acuoso de Triticum vulgare',
  'vitamina b5': 'Pantotenico Acido',
};
// Propuestas con equivalencia real pero mas de un candidato plausible: van a revision del dueno.
export const REVISION = {
  'hierro como sulfato ferroso': ['Hierro (ii) Sulfato', 'Hierro Sulfato Desecado'],
  'fosfato de sodio monobasico': ['Fosfato Monosodio Dihidrato', 'Sodio Fosfato'],
  'fosfato monosodico': ['Fosfato Monosodio Dihidrato', 'Sodio Fosfato'],
  'macrogol': ['Macrogol 3350', 'Macrogol 4000'],
};
// NO estan en el vademecum CIMA (existen en la realidad / no aprobadas en Espana, o son mezclas).
// OJO: solo entradas CONFIRMADAS por consulta a moleculas_referencias. Antes este listado
// incluia falsos negativos (butilescopolamina, diclofenac potasico, gluconato ferroso,
// bromexina) que SI existen en CIMA -> movidos a ALIAS el 2026-09-25.
// 2026-09-26: las 15 moleculas creadas (nitazoxanida, isoxsuprina, clemastina, lactasa,
// citrato de calcio, piperazina, magnesio glicinato, aminoacidos, alcohol polivinilico,
// sales de rehidratacion oral, lisado bacteriano, bacillus clausii, subsalicilato de bismuto,
// complejo de vitamina b, triticum vulgare) + los derechados por el dueno tambien salieron
// de esta lista -> ahora son ALIAS.
export const NO_CIMA = [
  'attapulgita', 'pectina', 'papaverina',
  'multivitaminico', 'multivitaminas', 'minerales',
  'lactobacillus lb inactivado y medio de cultivo fermentado',
  'solucion de ringer lactato', 'solucion ringer lactato',
  'monarc m', 'niazol',
];

