// Alias curados: propuesta del dueño -> nombre EXACTO en moleculas_referencias.
// Cada entrada se sustenta en el diagnostico de similitud (_diag_nomatch.txt).
export const ALIAS = {
  'acido acetilsalicilico': 'Acetilsalicilico Acido',
  'carbonato de calcio': 'Calcio Carbonato',
  'cloruro de sodio': 'Sodio Cloruro',
  'ciprofloxacina': 'Ciprofloxacino',
  'sildenafil': 'Sildenafilo',
  'acido valproico': 'Valproico Acido',
  'acido clavulanico': 'Clavulanico Acido',
  'acido ibandronico': 'Ibandronico Acido',
  'acido azelaico': 'Azelaico Acido',
  'acido ursodesoxicolico': 'Ursodeoxicolico Acido',
  'acido ursodeoxicolico': 'Ursodeoxicolico Acido',
  'citrato de potasio': 'Citrato Potasio',
  'trimetoprim': 'Trimetoprima',
  'hidroxicina': 'Hidroxizina',
  'hioscina butilescopolamina': 'Butilescopolamina Bromuro',
  'n butil bromuro de hioscina': 'Butilescopolamina Bromuro',
  'butil bromuro de hioscina': 'Butilescopolamina Bromuro',
  'vitamina d colecalciferol': 'Colecalciferol',
  'vitamina d3 colecalciferol': 'Colecalciferol',
  'vitamina c acido ascorbico': 'Ascorbico Acido',
  'metamizol dipirona': 'Metamizol',
  'peroxido de hidrogeno agua oxigenada': 'Peroxido De Hidrogeno',
  'iodopovidona': 'Povidona Iodada',
  'fosfato disodico': 'Fosfato Disodio',
  'fosfato de sodio dibasico': 'Fosfato Disodio',
  'fosfato de sodio': 'Sodio Fosfato',
  'bencilpenicilina benzatinica': 'Bencilpenicilina-benzatina',
  'bencilpenicilina procaina': 'Bencilpenicilina Procaina',
  'penicilina g procaina': 'Bencilpenicilina Procaina',
  'penicilina g sodica': 'Penicilina G',
  'piridoxina vitamina b6': 'Piridoxina',
  'benzydamina': 'Bencidamina',
  'senosidos': 'Senosidos A-b',
  'sulfadiazina de plata': 'Sulfadiazina Argentica',
  'hialuronato de sodio': 'Hialuronico Acido',
};
// Propuestas con equivalencia real pero mas de un candidato plausible: van a revision del dueno.
export const REVISION = {
  'hierro como sulfato ferroso': ['Hierro (ii) Sulfato', 'Hierro Sulfato Desecado'],
  'fosfato de sodio monobasico': ['Fosfato Monosodio Dihidrato', 'Sodio Fosfato'],
  'fosfato monosodico': ['Fosfato Monosodio Dihidrato', 'Sodio Fosfato'],
  'macrogol': ['Macrogol 3350', 'Macrogol 4000'],
};
// NO estan en el vademecum CIMA (existen en la realidad / no aprobadas en Espana, o son mezclas).
export const NO_CIMA = [
  'nitazoxanida', 'attapulgita', 'pectina', 'papaverina', 'isoxsuprina', 'clemastina',
  'cloruro de amonio', 'lactasa', 'multivitaminico', 'multivitaminas', 'minerales',
  'complejo b', 'sales de rehidratacion oral', 'alcohol polivinilico', 'subsalicilato de bismuto',
  'lactobacillus lb inactivado y medio de cultivo fermentado', 'complejo de vitamina b',
  'complejo vitamina b1 b2 b6 b12', 'lisado bacteriano', 'agua bidestilada', 'agua destilada',
  'agua para preparaciones inyectables', 'pediococcus acidilactici', 'bacillus clausii',
  'polisulfato de mucopolisacarido', 'aminoacidos cristalinos', 'aminoacidos',
  'solucion de ringer lactato', 'solucion ringer lactato', 'factor de coagulacion viii',
  'factor antihemofilico viii', 'bromexina clorhidrato', 'butilescopolamina bromuro',
  'gluconato ferroso', 'gluconato hierro', 'magnesio glicinato', 'diclofenac potasico',
  'n butil bromuro de hioscina bromuro', 'miconazol', 'sales de rehidratacion',
];
